name: CI/CD Wisk And Willow

on:
  push:
    branches:
      - "master"

jobs:
  EventManagement:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: krishnaprasad045/wiskandwillow-backend:latest
  depoly:
    needs: EventManagement
    runs-on: ubuntu-latest
    steps: 
      - name: set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and Deploy Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} \
            "sudo docker stop wiskandwillow || true && \
             sudo docker rm wiskandwillow || true && \
             sudo docker rmi krishnaprasad045/wiskandwillow-backend:latest || true && \
             sudo docker pull krishnaprasad045/wiskandwillow-backend:latest && \
             sudo docker run -d --name wiskandwillow -p 3000:3000 --env-file .env krishnaprasad045/wiskandwillow-backend:latest"
 
