name: CI/CD Wisk And Willow

on:
  push:
    branches:
      - "master"

jobs:
  EventManagement:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: krishnaprasad045/wiskandwillow-backend:latest

  DeployToEC2:
    runs-on: ubuntu-latest
    needs: EventManagement
    steps: 
      - name: Executing SSH commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Pull the latest Docker image from Docker Hub
            docker pull krishnaprasad045/wiskandwillow-backend:latest
            
            # Stop the existing container 
            docker stop wiskandwillow-backend || true
            
            # Remove the existing container 
            docker rm wiskandwillow-backend || true
            
            # Run the new container
            sudo docker run -d --env-file .env -p 3000:3000 krishnaprasad045/wiskandwillow-backend:latest
